### ISSUE TITLE
Sprint 10

### ISSUE THREAD

**Issue by mrprovoker** [TrustInTheLies/turbo-spoon#1]
Добрый день.

Отлично:
- Соблюдены требования к веткам, проект выложен на github.io
- Репозиторий чистый, оформлено README, удобно отформатирован index.html

Есть несколько проблем валидации.

**Надо исправить**:
- Проходит валидацию, а не должно такое имя: `Ян-` или такое `Ян--Ян`.
- Не проходит валидный email: `mysite@you.me.net`
- Проходит невалидный email: `mysite..1234@yahoo.com` (не может быть двух точек вподряд)
- Не все телефонные номера из задания проходят проверки. Сейчас в задании указано, что должны проходить данные номера:
```
+7 (123) 456-78-90
+7(925)900-90-90
+7(925) 900-90-90
+7 925-900-90-90
+79259009090
89259009090
```
- Проходит валидацию такой IP-адрес: http://www.255.255.255.255
- Не проходит валидацию такой валидный сайт: `http://mysite.ru:80`

Работу смогу принять только после устранения всех замечаний из пункта **Надо исправить**.

**Comment by mrprovoker** [comment]
Спасибо за правки, теперь стало значительно лучше. Есть еще несколько замечаний:


**Надо исправить**:
1. Проходит валидацию такое имя `Я-Я`. Однобуквенных имен не бывает
2. Проходит валидацию такой почтовый ящик (много пробелов до и после)               
>         mysite@com.my

Можно лучше:
- README получилось очень маленьким и коротким. Рекомендуется добавить подробное описание проекта, ссылку на проект на github.io, добавить инструкцию как развернуть проект локально.

Работу смогу принять только после устранения всех замечаний из пункта **Надо исправить**.

**Comment by TrustInTheLies** [comment]
Здравствуйте, с именем разобрался, но с емейлом не получается, согласно тестеру выражений, отступы в начале и конце не должны проходить, однако всё равно допускаются, можете подсказать, в какую сторону копать?

**Comment by mrprovoker** [comment]
Кажись это все-таки особенность `type="email"`, тогда снимаю требование, ок 👌

**Comment by TrustInTheLies** [comment]
Спасибо, вам тоже всего хорошего)
